version: '4.0'

services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123@store    
    healthcheck: # Adicionando healthcheck para garantir que o banco esteja pronto
      test: ["CMD", "sqlcmd", "-S", "localhost", "-U", "sa", "-P", "123@store", "-Q", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 3   





















  # ambev.developerevaluation.webapi:
  #   container_name: ambev_developer_evaluation_webapi
  #   image: ${DOCKER_REGISTRY-}ambevdeveloperevaluationwebapi
  #   build:
  #     context: .
  #     dockerfile: src/Ambev.DeveloperEvaluation.WebApi/Dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=8080
  #     - ASPNETCORE_HTTPS_PORTS=8081
  #   ports:
  #     - "8080"
  #     - "8081"
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  # ambev.developerevaluation.database:
  #   container_name: ambev_developer_evaluation_database
  #   image: postgres:13

  #   environment:
  #     POSTGRES_DB: developer_evaluation
  #     POSTGRES_USER: developer
  #     POSTGRES_PASSWORD: ev@luAt10n
  #   ports:
  #     - "5432"
  #   restart: unless-stopped

  # ambev.developerevaluation.nosql:
  #   container_name: ambev_developer_evaluation_nosql 
  #   image: mongo:8.0    
  #   environment:
  #       MONGO_INITDB_ROOT_USERNAME: developer
  #       MONGO_INITDB_ROOT_PASSWORD: ev@luAt10n
  #   ports:
  #     - "27017"

  # ambev.developerevaluation.cache:
  #   container_name: ambev_developer_evaluation_cache 
  #   image: redis:7.4.1-alpine     
  #   command: redis-server --requirepass ev@luAt10n
  #   environment:
  #      MONGO_INITDB_ROOT_USERNAME: developer
  #      MONGO_INITDB_ROOT_PASSWORD: ev@luAt10n
  #   ports:
  #      - "6379"